version: "3.4"

services:
  my-frontend:
    container_name: my-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true