version: "3.4"

services:
  my-frontend:
    container_name: my-frontend
    build:
      context: ./node-postgres/frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true